apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: staging
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer